import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import Weather from "../components/Weather";
import Background from "../assets/background.jpg";
import Search from "../components/Search";
import Modal from "../components/Modal";

export default function Home() {
  const [weather, setWeather] = useState({});
  const [isErrorModalOpen, setIsErrorModalOpen] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const openErrorModal = (errorMessage) => {
    setErrorMessage(errorMessage);
    setIsErrorModalOpen(true);
  };

  const closeErrorModal = () => {
    setIsErrorModalOpen(false);
    setErrorMessage("");
  };

  const fetchWeather = async (city, zip) => {
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&zip=${zip},us&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}&units=imperial`;

    if (!city && !zip) {
      openErrorModal("ERROR! Please enter a city name or zip code.");
      return;
    } else if (
      city.toLowerCase() === weather?.name?.toLowerCase() ||
      zip === weather?.zip?.toLowerCase()
    ) {
      openErrorModal(
        "ERROR! You already have weather data for this city or zip code."
      );
      return;
    } else {
      try {
        const response = await axios.get(url);
        if (response.status === 200) {
          setTimeout(() => {
            const weatherData = response.data;
            setWeather(weatherData);
          }, 1);
          setWeather({});
        } else {
          console.error("Failed to fetch weather data");
        }
      } catch (error) {
        console.error("An error occurred:", error);
      }
    }
  };

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Overlay */}
      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/15 z-[1]" />
      {/* Background image */}
      <Image src={Background} layout="fill" className="object-cover" />

      {/* Search */}
      <Search onSearch={fetchWeather} />
      {isErrorModalOpen && (
        <Modal message={errorMessage} onClose={closeErrorModal} />
      )}
      {weather.main && <Weather data={weather} />}
    </div>
  );
}
